// Package vt provides a bridge wrapper around a virtual terminal emulator.
// It receives raw PTY output and maintains screen state, exposing a simple
// API for reading terminal content and sending input.
package vt

import (
	"io"
	"strings"
	"sync"

	xvt "github.com/charmbracelet/x/vt"
)

// Terminal wraps a virtual terminal emulator, providing a simplified interface
// for feeding PTY output and reading screen state.
type Terminal struct {
	emu *xvt.SafeEmulator

	// Bridge pipe: emu.Read → pw → pr → our Read.
	// Allows Close to unblock Read without touching the Emulator directly,
	// avoiding a data race with SafeEmulator's internal mutex.
	pr *io.PipeReader
	pw *io.PipeWriter

	closeOnce sync.Once
}

// New creates a new Terminal with the given dimensions.
func New(width, height int) *Terminal {
	emu := xvt.NewSafeEmulator(width, height)
	pr, pw := io.Pipe()
	t := &Terminal{
		emu: emu,
		pr:  pr,
		pw:  pw,
	}
	go t.bridgeRead()
	return t
}

// bridgeRead continuously reads from the emulator and writes to our pipe.
func (t *Terminal) bridgeRead() {
	buf := make([]byte, 256)
	for {
		n, err := t.emu.Read(buf)
		if n > 0 {
			if _, werr := t.pw.Write(buf[:n]); werr != nil {
				return // pipe closed
			}
		}
		if err != nil {
			t.pw.CloseWithError(err)
			return
		}
	}
}

// Write feeds raw PTY output into the emulator.
func (t *Terminal) Write(p []byte) (int, error) {
	return t.emu.Write(p)
}

// Render returns the full screen as an ANSI-encoded string.
func (t *Terminal) Render() string {
	return t.emu.Render()
}

// RenderRegion returns a subset of rows from startRow to endRow (inclusive)
// as an ANSI-encoded string. Rows are zero-indexed.
func (t *Terminal) RenderRegion(startRow, endRow int) string {
	full := t.emu.Render()
	lines := strings.Split(full, "\n")

	if startRow < 0 {
		startRow = 0
	}
	if endRow >= len(lines) {
		endRow = len(lines) - 1
	}
	if startRow > endRow {
		return ""
	}

	return strings.Join(lines[startRow:endRow+1], "\n")
}

// Resize changes the terminal dimensions.
func (t *Terminal) Resize(width, height int) {
	t.emu.Resize(width, height)
}

// SendKey forwards a key event to the emulator.
func (t *Terminal) SendKey(key xvt.KeyPressEvent) {
	t.emu.SendKey(key)
}

// SendText forwards text input to the emulator.
func (t *Terminal) SendText(text string) {
	t.emu.SendText(text)
}

// Read reads escape sequences generated by SendKey/SendText from the emulator.
// Reads from a bridged pipe so that Close can unblock it without data races.
func (t *Terminal) Read(buf []byte) (int, error) {
	return t.pr.Read(buf)
}

// CursorPosition returns the current cursor position (x, y) where x is the
// column and y is the row, both zero-indexed.
func (t *Terminal) CursorPosition() (x, y int) {
	pos := t.emu.CursorPosition()
	return pos.X, pos.Y
}

// Width returns the terminal width in columns.
func (t *Terminal) Width() int {
	return t.emu.Width()
}

// Height returns the terminal height in rows.
func (t *Terminal) Height() int {
	return t.emu.Height()
}

// Close releases resources and unblocks any pending Read calls.
// Safe to call concurrently and multiple times.
func (t *Terminal) Close() {
	t.closeOnce.Do(func() {
		// Close our pipe to unblock any Read callers.
		// The bridgeRead goroutine will exit on next pw.Write error.
		t.pr.Close()
		t.pw.CloseWithError(io.ErrClosedPipe)
	})
}
